### ISSUE TITLE
Handling unhandled exceptions

### ISSUE THREAD

**Issue by mickeynp** [oisinmulvihill/evasion-director#2]
Each Agent should have one main method that lets you control and handle all exceptions raised by child methods of that Agent. Furthermore, there should be a way to kill the service if certain user-specified criteria are met - perhaps by raising a special exception to the controller, or by exiting the main method by returning False.

**Comment by oisinmulvihill** [comment]
I'm going to roll this into the 1.1.4 release I'm working on.

**Comment by oisinmulvihill** [comment]
resolved as part of #5
